### ISSUE TITLE
Change all instances of 'AddressBook' to 'CCACommander'

### ISSUE THREAD

**Issue by dylkaw** [AY2324S1-CS2103T-F11-1/tp#108]

**Comment by wr1159** [comment]
Just to clarify the scope, are we changing the `AddressBook.java` to `CCAComamnder.java` if so what should be the variable names? Currently we have `AddressBook addressBook = ... `, do we do `CCACommander ccaCommander`?

Edit: Do we change the package name too if so?

**Comment by SelwynAng** [comment]
Yes, we will need to change all instances of AddressBook to CCACommander, including variable names and package names.
