### ISSUE TITLE
[PE-D][Tester C] Inaccurate example in UG `createEvent`

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-F11-1/tp#204]
![image.png](https://raw.githubusercontent.com/Singa-pirate/ped/main/files/158471c5-4bac-4884-bb5c-cdd88c65103d.png)

Date formate given in UG's example for `createEvent` is in DD-MM-YYYY, while the actual implementation is YYYY-MM-DD.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Singa-pirate/ped#1

**Comment by wr1159** [comment]
Duplicate of #203, #201, #198
