### ISSUE TITLE
[PE-D][Tester C] Non data-changing commands require write permission

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F11-1/tp#220]
![image.png](https://raw.githubusercontent.com/Singa-pirate/ped/main/files/fa8c81a6-7ecd-47cd-bd6a-ad9e028859b7.png)

Steps to reproduce:
- set data file permission to read-only
- open app and execute `help` command

I think commands that makes no change to the data (e.g. `help`, `exit` and `list`) should be able to run even if the app has no write permission to the data file.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Singa-pirate/ped#3

**Comment by wr1159** [comment]
Out of scope / extreme user input as users are not expected to change the write/read permission of the data file.
