### ISSUE TITLE
[PE-D][Tester D] Cannot delete remark from enrolment

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F11-1/tp#228]
Unable to remove remarks from a student who has enrolled in an event if I added wrongly.
![image.png](https://raw.githubusercontent.com/ji-just-ji/ped/main/files/dae100fa-5392-45f8-852e-47aaa2b047b0.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ji-just-ji/ped#5

**Comment by wr1159** [comment]
Accepted Feature Flaw

To Change:
* Add into planned enhancements to allow users to remove remarks and hours in enrolments, and all optional fields in members and events.
